### ISSUE TITLE
coffee compiler is boundled to war 

### ISSUE THREAD

**Issue by stokito** [brian428/grails-coffeescript-compiler-plugin#16]
Do we really need that this plugin was in resulting war file?
Maybe it would be good to changt dependency

``` groovy
compile ":coffeescript-compiler:0.9.4"
```

to

``` groovy
build ":coffeescript-compiler:0.9.4"
```

**Comment by brian428** [comment]
The plugin is included in the war for two reasons: First, so that a guaranteed fresh generation of the JS can be done when the deployed war starts up. Second, to allow for spot changes to the deployed CoffeeScript to create updated JS files (to avoid deploying the entire war just to change one .coffee file).

So I'd say folks who don't want any of this should be able to exclude the plugin from the war with export=false or conditional logic (based on the current environment) in the BuildConfig.

Full disclosure: I've never done this (we deploy the plugin with our wars).
